services:
  myservice:
    container_name: crawler
    restart: unless-stopped
    hostname: crawler
    build: .
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /storage:/storage
    networks:
      - mysql_default

networks:
  mysql_default:
    external: true
